version: '3.5'

services:
  cache:
    image: redis
    ports:
      - "6379:6379"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    # this is for restart server when new change happen
    volumes:
      - .:/app
    command: bash -c "yarn dotenv -e .env.dev yarn prisma migrate deploy && yarn prisma generate && yarn start:dev"
    ports:
      - 3000:3000
    depends_on:
      - cache
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres-base:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-base: